version: "3.7"
services:
    # image com xdebug já setado para desenvolvimento
    api:
        image: astrotechdevs/php-nginx
        container_name: bankerize-api
        restart: unless-stopped
        working_dir: /app
        ports:
            - 8001:80
        volumes:
          - ./:/app
        networks:
            - bankerize-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
          - ENABLE_XDEBUG=true

    mariadb:
        image: mariadb:latest
        container_name: bankerize-mariadb
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--wait_timeout=28800',
            '--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
            '--sort_buffer_size=50485760' # 10MB
        ]
        restart: always
        ports:
        - "3384:3306"
        environment:
        - TZ=America/Sao_Paulo
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=bankerize
        networks:
        - bankerize-network
        volumes:
        - ./.docker/data:/var/lib/mysql

    redis:
        image: redis:6.2.6
        container_name: bankerize-redis
        restart: always
        ports:
        - "6879:6379"
        volumes:
        - ./.docker/redis:/data
        networks:
        - bankerize-network
        depends_on:
        - api

    rabbitmq:
        image: rabbitmq:3-management
        container_name: bankerize-rabbitmq
        hostname: 'rabbitmq-dev'
        ports:
        - "5672:5672"
        - "15672:15672"
        volumes:
        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker/rabbitmq/log/:/var/log/rabbitmq
        networks:
        - bankerize-network
        depends_on:
        - api

networks:
    bankerize-network:
        driver: bridge
